### PR TITLE
added md2json package

### PR DESCRIPTION
**Pull request by Zain-ul-din**
A helpful package that converts all links to JSON format so they can be used anywhere.

### CODE REVIEW

**Comment by Zain-ul-din** [comment]
@aborazmeh please can you merge this?

**Comment by aborazmeh** [comment]
I think this is out of scope and more related to code rather than the list itself. I prefer to keep the data and code separated here. Can't you fetch the list md file and convert it to the format most suitable for your project?

**Comment by Zain-ul-din** [comment]
@aborazmeh `md` file is working fine for me. My plan was to add search functionality but if you say 
> keep the data and code separated here.

i'll create new repo to convert you `md` to `json`. no problem!

**Comment by aborazmeh** [comment]
Thank you. I had that in mind from the beginning, and in my view, it's more logical to generate the Markdown file from a JSON file, but it's more convenient for non-programmers to edit this file if it was plain Markdown.

**Comment by Zain-ul-din** [comment]
Yes, I do agree with you our target audience is non-technical people.

**Comment by Zain-ul-din** [comment]
i've one question do you know any trusted sites where i can donate i've many people they want to donate.

**Comment by aborazmeh** [comment]
About the donations, I exclusively enlist international humanitarian organizations. I think you can try to find local ones which will help and they're mostly available.

**Pull request closed without merging**
