### PR TITLE
Added footer, abs URL and new website link

### PR DESCRIPTION
**Pull request by Zain-ul-din**
List of content I added

- Footer
- Absolute URL path for contributors
- BDS movement [Site link](https://bdsmovement.net/)

### CODE REVIEW

**Comment by Zain-ul-din** [comment]
AOA!
it would be nice if we could plan more thing to increase awareness among peoples and show our Solidarity with Palestinian people

**Comment by aborazmeh** [comment]
Thank you.
This repository started as a list of the best books I knew/read about the subject, and grew organically. I am open to all suggestions, though.

**Comment by Zain-ul-din** [comment]
I think we need to build some kind of community to support Palestine people.

**Comment by aborazmeh** [comment]
I am open to any suggestions or to collaborate in any projects which I can contribute to. What kind of community you are thinking of, and what purpose will it serve?

**Comment by Zain-ul-din** [comment]
It would be nice if we make a GitHub organization for Palestine support Projects. if you say I'll start it and invite you.

**Comment by aborazmeh** [comment]
If there are projects to work on, yes, but I don't think merely creating an organization on GitHub will do anything.

**Comment by Zain-ul-din** [comment]
I decided to add a news feed to [this site](https://github.com/Zain-ul-din/The-Palestinian-Side) what do you think we can use web scraping + social media APIS to create a news feed

**Pull request merged**
